{
 "title": "application",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "application",
    "query": {
     "query": "label_values(dubbo_application_info_total{},application_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(dubbo_application_info_total{application_name=\"$application\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "应用概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "调用成功率（作为消费者）",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(dubbo_consumer_requests_succeed_total{application_name=\"$application\"})   / sum(dubbo_consumer_requests_total{application_name=\"$application\"})  ) OR on() vector(NAN)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "被调用成功率（作为生产者）",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (dubbo_provider_requests_succeed_total{application_name=\"$application\"}) / sum (dubbo_provider_requests_total{application_name=\"$application\"}) OR  vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(dubbo_provider_qps_total{application_name=\"$application\"})",
     "legendFormat": "生产者被调用"
    },
    {
     "expr": "sum(dubbo_consumer_qps_total{application_name=\"$application\"})",
     "legendFormat": "消费者调用"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_consumer_rt_avg_milliseconds_aggregate{application_name=\"$application\"}>0)",
     "legendFormat": "调用 avg RT"
    },
    {
     "expr": "avg(dubbo_provider_rt_avg_milliseconds_aggregate{application_name=\"$application\"}>0)",
     "legendFormat": "被调用 avg RT"
    }
   ]
  },
  {
   "title": "并发",
   "type": "timeseries",
   "description": "当前正在处理的请求",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "dubbo_provider_requests_processing{application_name=\"$application\"} or vector(0)",
     "legendFormat": "生产者处理并发量"
    },
    {
     "expr": "dubbo_consumer_requests_processing{application_name=\"$application\"} or vector(0)",
     "legendFormat": "消费者调用并发量"
    }
   ]
  },
  {
   "title": "最近调用RT（作为生产者）",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dubbo_provider_rt_milliseconds_last{application_name=\"$application\"})",
     "legendFormat": "实时时延"
    }
   ]
  },
  {
   "title": "调用总览(作为消费者 2min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum (increase(dubbo_consumer_requests_total{application_name=\"$application\"}[2m])>0) OR vector(0)",
     "legendFormat": "总数"
    },
    {
     "expr": "sum(increase(dubbo_consumer_requests_succeed_total{application_name=\"$application\"}[2m])>0) OR vector(0)",
     "legendFormat": "成功数"
    },
    {
     "expr": "sum(increase(dubbo_consumer_requests_failed_total{application_name=\"$application\"}[2m])>0) OR vector(0)",
     "legendFormat": "失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_business_failed_total{application_name=\"$application\"}[2m])>0)  OR vector(0)",
     "legendFormat": "业务原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_timeout_total{application_name=\"$application\"}[2m])>0) OR vector(0)",
     "legendFormat": "超时数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_unknown_failed_tota{application_name=\"$application\"}[2m])>0) OR vector(0)",
     "legendFormat": "未知原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_service_unavailable_total{application_name=\"$application\"}[2m])>0) OR vector(0)",
     "legendFormat": "服务不可用数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_network_total{application_name=\"$application\"}[2m])>0) OR vector(0)",
     "legendFormat": "网络错误数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_codec_total{application_name=\"$application\"}[2m])>0) OR vector(0)",
     "legendFormat": "编解码错误数"
    }
   ]
  },
  {
   "title": "被调用总览(作为生产者 2min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "sum (increase(dubbo_provider_requests_total{application_name=\"$application\"}[2m])) OR vector(0)",
     "legendFormat": "总数"
    },
    {
     "expr": "sum(increase(dubbo_provider_requests_succeed_total{application_name=\"$application\"}[2m]) ) OR vector(0)",
     "legendFormat": "成功数"
    },
    {
     "expr": "sum(increase(dubbo_provider_requests_failed_total{application_name=\"$application\"}[2m]) ) OR vector(0)",
     "legendFormat": "失败数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_business_failed_total{application_name=\"$application\"}[2m])) OR vector(0)",
     "legendFormat": "业务原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_timeout_total{application_name=\"$application\"}[2m])) OR vector(0)",
     "legendFormat": "超时数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_unknown_failed_tota{application_name=\"$application\"}[2m])) OR vector(0)",
     "legendFormat": "未知原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_failed_service_unavailable_total{application_name=\"$application\"}[2m])) OR vector(0)",
     "legendFormat": "服务不可用数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_failed_network_total{application_name=\"$application\"}[2m])) OR vector(0)",
     "legendFormat": "网络错误数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_failed_codec_total{application_name=\"$application\"}[2m])) OR vector(0)",
     "legendFormat": "序列化错误数"
    }
   ]
  },
  {
   "title": "最近调用RT（作为消费者）",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dubbo_consumer_rt_milliseconds_last{application_name=\"$application\"})",
     "legendFormat": "实时时延"
    }
   ]
  },
  {
   "title": "QPS (生产者 & 消费者)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "被调用QPS（作为生产者）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "avg(sum(dubbo_provider_qps_total{application_name=\"$application\"}) by (instance))",
       "legendFormat": "平均QPS"
      },
      {
       "expr": "sum(dubbo_provider_qps_total{application_name=\"$application\"}) by (instance, pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "调用QPS（作为消费者）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "avg(sum(dubbo_consumer_qps_total{application_name=\"$application\"}) by (instance))",
       "legendFormat": "平均QPS"
      },
      {
       "expr": "sum(dubbo_consumer_qps_total{application_name=\"$application\"}) by (instance, pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "应用调用详情（作为消费者）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "调用总数(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_total{application_name=\"$application\"}[2m])>0)",
       "legendFormat": "总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_total{application_name=\"$application\"}[2m])>0) by (instance,pod) ",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "调用成功(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 37 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_succeed_total{application_name=\"$application\"}[2m])>0) ",
       "legendFormat": "成功总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_succeed_total{application_name=\"$application\"}[2m])>0) by (instance,pod) ",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "调用失败(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 37 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_total{application_name=\"$application\"}[2m])>0) ",
       "legendFormat": "失败总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_failed_total{application_name=\"$application\"}[2m])>0) by (instance,pod) ",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "业务原因错误(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_business_failed_total{application_name=\"$application\"}[2m]))",
       "legendFormat": "业务原因错误总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_business_failed_total{application_name=\"$application\"}[2m])) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "超时错误(Consumer 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 47 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_timeout_total{application_name=\"$application\"}[2m])) ",
       "legendFormat": "超时错误总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_timeout_total{application_name=\"$application\"}[2m])) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "服务不可用错误(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 47 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_service_unavailable_total{application_name=\"$application\"}[2m])) >0",
       "legendFormat": "服务不可用总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_failed_service_unavailable_total{application_name=\"$application\"}[2m])) by (instance,pod) >0",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "网络错误(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_network_total{application_name=\"$application\"}[2m])) ",
       "legendFormat": "网络错误总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_failed_network_total{application_name=\"$application\"}[2m])) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "序列化错误(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 57 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_codec_total{application_name=\"$application\"}[2m])) ",
       "legendFormat": "序列化错误总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_failed_codec_total{application_name=\"$application\"}[2m])) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "未知原因错误(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 57 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_unknown_failed_tota{application_name=\"$application\"}[2m])) >0",
       "legendFormat": "未知原因失败总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_unknown_failed_total{application_name=\"$application\"}[2m])) by (instance,pod)>0",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "应用被调用详情（作为生产者）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "被调用总数(作为生产者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_total{application_name=\"$application\"}[2m])) >0",
       "legendFormat": "总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_total{application_name=\"$application\"}[2m])) by (instance,pod)>0",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "被调用成功(作为生产者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_succeed_total{application_name=\"$application\"}[2m])) >0",
       "legendFormat": "成功数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_succeed_total{application_name=\"$application\"}[2m])) by (instance,pod)>0",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "被调用失败(作为生产者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_total{application_name=\"$application\"}[2m]))>0",
       "legendFormat": "失败总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_failed_total{application_name=\"$application\"}[2m])) by (instance,pod)>0",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "业务原因错误(作为生产者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_business_failed_total{application_name=\"$application\"}[2m]))>0",
       "legendFormat": "业务原因错误总数"
      },
      {
       "expr": "sum(increase (dubbo_provider_requests_business_failed_total{application_name=\"$application\"} [2m]) )by(instance,pod)>0\r\n",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "超时错误(作为生产者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_timeout_total{application_name=\"$application\"}[2m]))",
       "legendFormat": "超时总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_timeout_total{application_name=\"$application\"}[2m])) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "服务不可用错误(作为生产者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 31 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_service_unavailable_total{application_name=\"$application\"}[2m]))",
       "legendFormat": "服务不可用总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_failed_service_unavailable_total{application_name=\"$application\"}[2m])) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "网络错误(作为生产者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_network_total{application_name=\"$application\"}[2m]))>0",
       "legendFormat": "网络错误总数"
      },
      {
       "expr": "sum(label_replace(increase(dubbo_provider_requests_failed_network_total{application_name=\"$application\"}[2m]), \"instance\", \"$1\", \"instance\", \"(.*):.*\")) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "序列化错误(作为生产者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 41 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_codec_total{application_name=\"$application\"}[2m])) >0",
       "legendFormat": "序列化错误总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_failed_codec_total{application_name=\"$application\"}[2m])) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "未知原因错误(作为生产者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 41 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_unknown_failed_total{application_name=\"$application\"}[2m])) >0",
       "legendFormat": "未知原因失败总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_unknown_failed_total{application_name=\"$application\"}[2m])) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "应用请求时延RT (Consumer)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "调用 RT P95(作为消费者)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(dubbo_consumer_rt_milliseconds_p95{application_name=\"$application\",}>0) by(instance,pod)",
       "legendFormat": "{{instance}}_{pod}"
      }
     ]
    },
    {
     "title": "调用 RT P99(作为消费者)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(dubbo_consumer_rt_milliseconds_p99{application_name=\"$application\",}>0) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "应用响应时延RT (Provider)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "RT P95(作为生产者)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(dubbo_provider_rt_milliseconds_p95{application_name=\"$application\",}>0) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "响应平均时延 P99(Provider)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(dubbo_provider_rt_milliseconds_p99{application_name=\"$application\",}>0) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "注册中心",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "注册实例次数",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(dubbo_registry_register_requests_total{application_name=\"$application\"})",
       "legendFormat": "注册总次数"
      },
      {
       "expr": "sum(dubbo_registry_register_requests_succeed_total{application_name=\"$application\"})OR on() vector(0)",
       "legendFormat": "注册成功数"
      },
      {
       "expr": "sum(dubbo_registry_register_requests_failed_total{application_name=\"$application\"})  OR on() vector(0)",
       "legendFormat": "注册失败数"
      }
     ]
    },
    {
     "title": "实例注册时长",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "dubbo_register_rt_milliseconds_sum{application_name=\"$application\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "deprecated",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "实例",
     "type": "table",
     "description": "只有启动成功的实例并接入监控的才会显示",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 139 },
     "targets": [
      {
       "expr": "count (dubbo_application_info_total{application_name=\"$application\"}) by(application_name,instance,application_version,host,pod,clusterName)",
       "legendFormat": "实例总数"
      }
     ]
    },
    {
     "title": "提供接口",
     "type": "table",
     "description": "有请求的接口才会展示",
     "gridPos": { "h": 7, "w": 7, "x": 10, "y": 139 },
     "targets": [
      {
       "expr": "count by(interface,version) (dubbo_provider_requests_total{application_name=\"$application\",interface!~\"org.apache.dubbo.metrics.service.MetricsService|org.apache.dubbo.metadata.MetadataService\"})"
      }
     ]
    },
    {
     "title": "消费接口",
     "type": "table",
     "description": "有请求的接口才会展示",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 139 },
     "targets": [
      {
       "expr": "count by(interface,version) (dubbo_consumer_requests_total{application_name=\"$application\",interface!~\"org.apache.dubbo.metrics.service.MetricsService|org.apache.dubbo.metadata.MetadataService\"})"
      }
     ]
    },
    {
     "title": "实例版本分布",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 146 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by(application_version)(dubbo_application_info_total{application_name=\"$application\",instance=~\".*\"})",
       "legendFormat": "{{application_version}}"
      }
     ]
    },
    {
     "title": "提供接口数",
     "type": "stat",
     "description": "准确的提供接口数量",
     "gridPos": { "h": 5, "w": 3, "x": 2, "y": 146 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by(interface) (dubbo_provider_requests_total{application_name=\"$application\",interface!~\"org.apache.dubbo.metrics.service.MetricsService|org.apache.dubbo.metadata.MetadataService\"}))"
      }
     ]
    },
    {
     "title": "消费接口数",
     "type": "stat",
     "description": "准确的提供接口数量",
     "gridPos": { "h": 5, "w": 3, "x": 5, "y": 146 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by(interface) (dubbo_consumer_requests_total{application_name=\"$application\",interface!~\"org.apache.dubbo.metrics.service.MetricsService|org.apache.dubbo.metadata.MetadataService\"}))"
      }
     ]
    },
    {
     "title": "响应时延热点图 (Provider)",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 151 },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(dubbo_provider_rt_milliseconds_histogram_seconds_bucket{application_name=\"$application\",method=\"getItem\"}[2m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "instance",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "application",
    "query": {
     "query": "label_values(dubbo_application_info_total{},application_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(dubbo_application_info_total{application_name=\"$application\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "实例概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "调用成功率（作为消费者）",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(dubbo_consumer_requests_succeed_total{application_name=\"$application\",instance=\"$instance\"})   / sum(dubbo_consumer_requests_total{application_name=\"$application\",instance=\"$instance\"})  ) OR on() vector(NAN)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "被调用成功率（作为生产者）",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (dubbo_provider_requests_succeed_total{application_name=\"$application\",instance=\"$instance\"}) / sum (dubbo_provider_requests_total{application_name=\"$application\",instance=\"$instance\"}) OR  vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(dubbo_provider_qps_total{application_name=\"$application\",instance=\"$instance\"})",
     "legendFormat": "提供端QPS"
    },
    {
     "expr": "sum(dubbo_consumer_qps_total{application_name=\"$application\",instance=\"$instance\"})",
     "legendFormat": "消费者QPS"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_consumer_rt_avg_milliseconds_aggregate{application_name=\"$application\",instance=\"$instance\",}>0)",
     "legendFormat": "消费者RT"
    },
    {
     "expr": "avg(dubbo_provider_rt_avg_milliseconds_aggregate{application_name=\"$application\",instance=\"$instance\",}>0)",
     "legendFormat": "提供端RT"
    }
   ]
  },
  {
   "title": "并发",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum (dubbo_provider_requests_processing{instance=\"$instance\"} ) OR vector (0)",
     "legendFormat": "生产者处理并发量"
    },
    {
     "expr": "sum(dubbo_consumer_requests_processing{instance=\"$instance\"}) OR vector (0)",
     "legendFormat": "消费者调用并发量"
    }
   ]
  },
  {
   "title": "最近被调用RT（作为生产者）",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dubbo_provider_rt_milliseconds_last{application_name=\"$application\",instance=\"$instance\"}",
     "legendFormat": "实时时延"
    }
   ]
  },
  {
   "title": "实例调用(作为消费者 2min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum (increase(dubbo_consumer_requests_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "总数"
    },
    {
     "expr": "sum(increase(dubbo_consumer_requests_succeed_total{application_name=\"$application\",instance=\"$instance\"}[2m]) ) OR vector(0)",
     "legendFormat": "成功数"
    },
    {
     "expr": "sum(increase(dubbo_consumer_requests_failed_total{application_name=\"$application\",instance=\"$instance\"}[2m]) ) OR vector(0)",
     "legendFormat": "失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_business_failed_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "业务原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_timeout_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "请求超时数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_unknown_failed_tota{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "未知原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_service_unavailable_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "服务不可用数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_network_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "网络错误数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_codec_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "序列化错误数"
    }
   ]
  },
  {
   "title": "实例被调用(作为生产者 2min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "sum (increase(dubbo_provider_requests_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "总数"
    },
    {
     "expr": "sum(increase(dubbo_provider_requests_succeed_total{application_name=\"$application\",instance=\"$instance\"}[2m]) ) OR vector(0)",
     "legendFormat": "成功数"
    },
    {
     "expr": "sum(increase(dubbo_provider_requests_failed_total{application_name=\"$application\",instance=\"$instance\"}[2m]) ) OR vector(0)",
     "legendFormat": "失败数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_business_failed_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "业务原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_timeout_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "超时数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_unknown_failed_tota{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "未知原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_failed_service_unavailable_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "服务不可用数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_failed_network_total{application_name=\"$application\"}[2m])) OR vector(0)",
     "legendFormat": "网络错误数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_failed_codec_total{application_name=\"$application\"}[2m])) OR vector(0)",
     "legendFormat": "序列化错误数"
    }
   ]
  },
  {
   "title": "最近调用时延（作为消费者）",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dubbo_consumer_rt_milliseconds_last{application_name=\"$application\",instance=\"$instance\"}",
     "legendFormat": "实时时延"
    }
   ]
  },
  {
   "title": "实例QPS 详情（生产者&消费者）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "提供接口QPS（作为生产者）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum(dubbo_provider_qps_total{application_name=\"$application\",instance=\"$instance\",}) by (interface)",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "依赖接口QPS（作为消费者）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "sum(dubbo_consumer_qps_total{application_name=\"$application\",instance=\"$instance\",}) by (interface)",
       "legendFormat": "{{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "实例被调用详情（作为生产者）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "请求总数(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_total{instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "请求总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_total{instance=\"$instance\",}[2m])) by (interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "请求成功(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_succeed_total{instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "请求成功总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_succeed_total{instance=\"$instance\",}[2m])) by (interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "请求失败(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_total{instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "请求失败总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_failed_total{instance=\"$instance\",}[2m])) by (interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "业务原因错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_business_failed_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface) or vector(0)",
       "legendFormat": "业务原因错误总数"
      },
      {
       "expr": "sum (increase(dubbo_provider_requests_business_failed_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface)",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "超时错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_timeout_total{application_name=\"$application\",instance=\"$instance\",}[2m]))  or vector(0)",
       "legendFormat": "超时错误总数"
      },
      {
       "expr": "sum (increase(dubbo_provider_requests_timeout_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "服务不可用错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_service_unavailable_total{application_name=\"$application\",instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "服务不可用错误总数"
      },
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_service_unavailable_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "网络错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_network_total{application_name=\"$application\",instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "网络错误总数"
      },
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_network_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface)  ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "序列化错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_codec_total{application_name=\"$application\",instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "序列化错误总数"
      },
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_codec_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface)  ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "未知原因错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_unknown_failed_tota{application_name=\"$application\",instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "未知原因错误总数"
      },
      {
       "expr": "sum (increase(dubbo_provider_requests_unknown_failed_tota{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface)",
       "legendFormat": "{{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "实例调用详情（作为消费者）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "调用总数(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_total{instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "调用总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_total{instance=\"$instance\",}[2m])) by (interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "调用成功(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_succeed_total{instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "调用成功总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_succeed_total{instance=\"$instance\",}[2m])) by (interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "调用失败(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_total{instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "调用失败总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_failed_total{instance=\"$instance\",}[2m])) by (interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "业务原因错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_business_failed_total{application_name=\"$application\",instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "业务原因错误"
      },
      {
       "expr": "sum (increase(dubbo_consumer_requests_business_failed_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface)",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "超时错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_timeout_total{application_name=\"$application\",instance=\"$instance\",}[2m]))  or vector(0)",
       "legendFormat": "超时错误"
      },
      {
       "expr": "sum (increase(dubbo_consumer_requests_timeout_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface)",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "服务不可用错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_service_unavailable_total{application_name=\"$application\",instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "服务不可用"
      },
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_service_unavailable_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "网络错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_network_total{application_name=\"$application\",instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "网络错误总数"
      },
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_network_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface)",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "序列化错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_codec_total{application_name=\"$application\",instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "序列化错误总数"
      },
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_codec_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "未知原因错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_unknown_failed_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface) or vector(0)",
       "legendFormat": "未知原因错误"
      },
      {
       "expr": "sum (increase(dubbo_consumer_requests_unknown_failed_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "实例 RT 详情(作为生产者)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "RT P95",
     "type": "timeseries",
     "description": "作为生产者，响应上游服务的95%的请求的RT",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(dubbo_provider_rt_milliseconds_p95{application_name=\"$application\",instance=\"$instance\",}>0)",
       "legendFormat": "avgRT P95 "
      },
      {
       "expr": "dubbo_provider_rt_milliseconds_p95{application_name=\"$application\",instance=\"$instance\",}>0",
       "legendFormat": "{{interface}}.{{method}} P95 RT"
      }
     ]
    },
    {
     "title": "RT P99",
     "type": "timeseries",
     "description": "作为生产者，响应上游服务的99%的请求的RT",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(dubbo_provider_rt_milliseconds_p99{application_name=\"$application\",instance=\"$instance\",}>0)",
       "legendFormat": "avgRT P99"
      },
      {
       "expr": "dubbo_provider_rt_milliseconds_p99{application_name=\"$application\",instance=\"$instance\",}>0",
       "legendFormat": "{{interface}}.{{method}} P99 RT"
      }
     ]
    },
    {
     "title": "min RT",
     "type": "timeseries",
     "description": "作为生产者，响应上游服务请求的最小RT",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_provider_rt_min_milliseconds_aggregate{application_name=\"$application\",instance=\"$instance\",}>0",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "max RT",
     "type": "timeseries",
     "description": "作为生产者，响应上游服务请求的最大RT",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_provider_rt_min_milliseconds_aggregate{application_name=\"$application\",instance=\"$instance\",}>0",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "实例 RT 详情 (作为消费者)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "RT P95",
     "type": "timeseries",
     "description": "作为消费者，调用下游服务时95%的请求的RT",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_consumer_rt_milliseconds_p95{application_name=\"$application\",instance=\"$instance\",}>0",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "RT P99(Consumer)",
     "type": "timeseries",
     "description": "作为消费者，调用下游服务时99%的请求的RT",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(dubbo_consumer_rt_milliseconds_p99{application_name=\"$application\",instance=\"$instance\",}>0)",
       "legendFormat": "avgRT P99"
      },
      {
       "expr": "dubbo_consumer_rt_milliseconds_p99{application_name=\"$application\",instance=\"$instance\",}>0",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "min RT ",
     "type": "timeseries",
     "description": "作为消费者，调用下游服务的最小RT",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_consumer_rt_min_milliseconds_aggregate{application_name=\"$application\",instance=\"$instance\",}>0",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "max RT",
     "type": "timeseries",
     "description": "作为消费者，调用下游服务的最大RT",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_consumer_rt_max_milliseconds_aggregate{application_name=\"$application\",instance=\"$instance\",}>0",
       "legendFormat": "{{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dubbo线程池",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "线程池核心",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "dubbo_thread_pool_core_size{application_name=\"$application\",instance=\"$instance\",thread_pool_name!~\".*MetadataService.*|.*MetricsService.*\"}",
       "legendFormat": "{{thread_pool_name}}"
      }
     ]
    },
    {
     "title": "线程池活跃",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "dubbo_thread_pool_active_size{application_name=\"$application\",instance=\"$instance\",thread_pool_name!~\".*MetadataService.*|.*MetricsService.*\"}",
       "legendFormat": "{{thread_pool_name}}"
      }
     ]
    },
    {
     "title": "线程池队列",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "dubbo_thread_pool_queue_size{application_name=\"$application\",instance=\"$instance\",thread_pool_name!~\".*MetadataService.*|.*MetricsService.*\"}",
       "legendFormat": "{{thread_pool_name}}"
      }
     ]
    },
    {
     "title": "线程池最大",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "dubbo_thread_pool_largest_size{application_name=\"$application\",instance=\"$instance\",thread_pool_name!~\".*MetadataService.*|.*MetricsService.*\"}",
       "legendFormat": "{{thread_pool_name}}"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "service",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(dubbo_provider_requests_total{},interface)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(dubbo_provider_requests_total{interface=\"$service\"},method)"
    }
   }
  ]
 },
 "panels": [
  { "title": "接口总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "调用成功率（Consumer）",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(dubbo_consumer_requests_succeed_total{interface=\"$service\",method=~\"$method\"})   / sum(dubbo_consumer_requests_total{interface=\"$service\",method=~\"$method\"})  ) OR on() vector(NAN)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "被调用成功率（Provider）",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(dubbo_provider_requests_succeed_total{interface=\"$service\",method=~\"$method\"})   / sum(dubbo_provider_requests_total{interface=\"$service\",method=~\"$method\"})  ) OR on() vector(NAN)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(dubbo_consumer_qps_total{interface=\"$service\",method=~\"$method\"})",
     "legendFormat": "调用（消费者视角）"
    },
    {
     "expr": "sum(dubbo_provider_qps_total{interface=\"$service\",method=~\"$method\"})",
     "legendFormat": "被调用（生产者视角）"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_consumer_rt_avg_milliseconds_aggregate{interface=\"$service\",method=~\"$method\"}>0)",
     "legendFormat": "调用 avg RT"
    },
    {
     "expr": "avg(dubbo_provider_rt_avg_milliseconds_aggregate{interface=\"$service\",method=~\"$method\"}>0)",
     "legendFormat": "被调用 avg RT"
    }
   ]
  },
  {
   "title": "并发",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum (dubbo_provider_requests_processing{interface=\"$service\"} ) OR vector (0)",
     "legendFormat": "生产者处理并发量"
    },
    {
     "expr": "sum(dubbo_consumer_requests_processing{interface=\"$service\"}) OR vector (0)",
     "legendFormat": "消费者调用并发量"
    }
   ]
  },
  {
   "title": "最近被调用时延（RT）",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dubbo_provider_rt_milliseconds_last{interface=\"$service\",method=~\"$method\"})",
     "legendFormat": "实时时延"
    }
   ]
  },
  {
   "title": "被调用总览(生产者视角 2min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum (increase(dubbo_provider_requests_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "总数"
    },
    {
     "expr": "sum(increase(dubbo_provider_requests_succeed_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "成功数"
    },
    {
     "expr": "sum(increase(dubbo_consumer_requests_failed_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "请求失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_business_failed_total{interface=\"$service\"}[2m])>0)  OR vector(0)",
     "legendFormat": "业务原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_timeout_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "超时数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_unknown_failed_tota{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "未知原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_service_unavailable_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "服务不可用数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_network_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "网络错误数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_codec_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "序列化错误数"
    }
   ]
  },
  {
   "title": "调用总览(消费者视角 2min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "sum (increase(dubbo_consumer_requests_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "总数"
    },
    {
     "expr": "sum(increase(dubbo_consumer_requests_succeed_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "成功数"
    },
    {
     "expr": "sum(increase(dubbo_consumer_requests_failed_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "请求失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_business_failed_total{interface=\"$service\"}[2m])>0)  OR vector(0)",
     "legendFormat": "业务原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_timeout_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "超时数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_unknown_failed_tota{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "未知原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_service_unavailable_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "服务不可用数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_network_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "网络错误数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_codec_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "编解码错误数"
    }
   ]
  },
  {
   "title": "最近调用时延（RT）",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dubbo_consumer_rt_milliseconds_last{interface=\"$service\",method=~\"$method\"})",
     "legendFormat": "实时时延"
    }
   ]
  },
  {
   "title": "接口QPS详情（生产者&消费者）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "被调用QPS （生产者视角）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(dubbo_provider_qps_total{interface=\"$service\"}) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "调用QPS（消费者视角）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(dubbo_consumer_qps_total{interface=\"$service\"}) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "接口被调用详情（生产者详情）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "请求总数(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_total{interface=\"$service\"}[2m])) or vector(0)",
       "legendFormat": "请求总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method) ",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "请求成功(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_succeed_total{interface=\"$service\"}[2m])) or vector(0) ",
       "legendFormat": "请求成功总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_succeed_total{interface=\"$service\",method=~\"$method\"}[2m])>0) by (method) ",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "请求失败(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_total{interface=\"$service\"}[2m])) or vector(0)",
       "legendFormat": "请求失败数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_failed_total{interface=\"$service\",method=~\"$method\"}[2m])>0) by (method) ",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "业务原因错误(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_business_failed_total{interface=\"$service\"}[2m])) or vector(0)",
       "legendFormat": "业务原因错误总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_business_failed_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "请求超时错误(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_timeout_total{interface=\"$service\"}[2m])) OR vector(0)",
       "legendFormat": "请求超时总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_timeout_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "服务不可用错误(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_service_unavailable_total{interface=\"$service\"}[2m])) ",
       "legendFormat": "服务不可用总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_failed_service_unavailable_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method) ",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "网络错误(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_network_total{interface=\"$service\"}[2m])) OR vector(0)",
       "legendFormat": "网络错误总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_failed_network_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "序列化错误(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_codec_total{interface=\"$service\"}[2m])) OR vector(0)",
       "legendFormat": "序列化错误总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_failed_codec_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "未知原因错误(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_unknown_failed_total{interface=\"$service\"}[2m])) OR vector(0)",
       "legendFormat": "未知原因失败总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_unknown_failed_total{interface=\"$service\",method=~\"method\"}[2m])) by (mehtod)",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "接口调用详情（消费者视角）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "请求总数(消费者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_total{interface=\"$service\"}[2m])) or vector(0)",
       "legendFormat": "请求总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method) ",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "请求成功(消费者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_succeed_total{interface=\"$service\"}[2m])) or vector(0) ",
       "legendFormat": "请求成功数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_succeed_total{interface=\"$service\",method=~\"$method\"}[2m])>0) by (method) ",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "请求失败(消费者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_total{interface=\"$service\"}[2m])) or vector(0)",
       "legendFormat": "请求失败数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_failed_total{interface=\"$service\",method=~\"$method\"}[2m])>0) by (method) ",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "业务原因错误(消费者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_business_failed_total{interface=\"$service\"}[2m])) or vector(0)",
       "legendFormat": "业务原因错误总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_business_failed_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "请求超时错误(消费者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_timeout_total{interface=\"$service\"}[2m])) OR vector(0)",
       "legendFormat": "请求超时总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_timeout_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "服务不可用错误(消费者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_service_unavailable_total{interface=\"$service\"}[2m])) ",
       "legendFormat": "服务不可用总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_failed_service_unavailable_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method) ",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "网络错误(消费者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_network_total{interface=\"$service\"}[2m])) OR vector(0)",
       "legendFormat": "网络错误总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_failed_network_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "序列化错误(消费者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_codec_total{interface=\"$service\"}[2m])) OR vector(0)",
       "legendFormat": "序列化错误总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_failed_codec_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "未知原因错误(消费者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_unknown_failed_total{interface=\"$service\"}[2m])) OR vector(0)",
       "legendFormat": "未知原因失败总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_unknown_failed_total{interface=\"$service\",method=~\"method\"}[2m])) by (mehtod)",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  { "title": "接口RT详情（生产者视角）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "RT P95",
   "type": "timeseries",
   "description": "生产者响应 此接口的95%请求的RT",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_provider_rt_milliseconds_p95{interface=\"$service\",method=~\"$method\"}>0) by (method) ",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RT P99",
   "type": "timeseries",
   "description": "生产者响应 此接口的99%请求的RT",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_provider_rt_milliseconds_p99{interface=\"$service\",method=~\"$method\"}>0) by (method) ",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "min RT",
   "type": "timeseries",
   "description": "生产者响应此接口请求的最小RT",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_provider_rt_min_milliseconds_aggregate{interface=\"$service\",method=~\"$method\"}>0) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": " max RT",
   "type": "timeseries",
   "description": "生产者响应此接口请求的最大RT",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_provider_rt_max_milliseconds_aggregate{interface=\"$service\",method=~\"$method\"}>0) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "接口 RT详情（消费者视角）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "RT P95",
   "type": "timeseries",
   "description": "消费者调用此接口时95%的请求的RT",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_consumer_rt_milliseconds_p95{interface=\"$service\",method=~\"$method\"}>0) by (method) ",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RT P99",
   "type": "timeseries",
   "description": "消费者调用此接口时99%的请求的RT",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_consumer_rt_milliseconds_p99{interface=\"$service\",method=~\"$method\"}>0) by (method) ",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "min RT",
   "type": "timeseries",
   "description": "消费者调用此接口的最小RT",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_consumer_rt_min_milliseconds_aggregate{interface=\"$service\",method=~\"$method\"}>0) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "max RT",
   "type": "timeseries",
   "description": "消费者调用此接口最大RT",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_consumer_rt_max_milliseconds_aggregate{interface=\"$service\",method=~\"$method\"}>0) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "deprecated",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "接口方法",
     "type": "table",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "count by(method) (dubbo_provider_requests_total{interface=\"$service\"})"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "application",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "jaeger" },
   { "name": "application" }
  ]
 },
 "panels": [
  {
   "title": "Trace Table",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "service": "${application}" }
   ]
  }
 ]
}
{
 "title": "instance",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "jaeger" },
   { "name": "application", "label": "application" },
   { "name": "instance" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "service": "${application}", "tags": "net.peer.name=${instance}" }
   ]
  }
 ]
}
{
 "title": "service",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "jaeger" },
   { "name": "application", "label": "application" },
   { "name": "service", "label": "service" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "service": "${application}", "tags": "rpc.service=${service}" }
   ]
  }
 ]
}