# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbo-admin
  namespace: dubbo-system
  labels:
    app: dubbo-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbo-admin
  template:
    metadata:
      name: dubbo-admin
      labels:
        app: dubbo-admin
    spec:
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        runAsNonRoot: true
      serviceAccountName: dubbo-admin
      containers:
        - name: dubbo-admin
          image: apache/dubbo-admin:0.7.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/dubbo-admin
              name: dubbo-admin-config
              readOnly: true
            - name: dubbo-admin-logs
              mountPath: /app/logs
          command:
            - /app/dubbo-admin
          args:
            - run
            - -c
            - /etc/dubbo-admin/dubbo-admin.yaml
          livenessProbe:
            httpGet:
              port: 5680
              path: /healthy
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 5680
              path: /ready
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8888
              protocol: TCP
      restartPolicy: Always
      volumes:
        - name: dubbo-admin-config
          configMap:
            name: dubbo-admin-config
        - name: dubbo-admin-logs
          # You can replace it with hostPath or pvc to store logs.
          emptyDir: { }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dubbo-admin-config
  namespace: dubbo-system

data:
  dubbo-admin.yaml: |
    observability:
      grafana: http://grafana.monitoringg.svc:3000
      prometheus: http://prometheus-k8s.monitoring.svc:9090/
    console:
      auth:
        user: admin
        password: dubbo@2025
        expirationTime: 3600
    discovery:
      - type: nacos2
        name: nacos2.5-standalone
        id: nacos2.5
        address:
          registry: nacos://nacos.dubbo-system.svc:8848?username=nacos&password=nacos
          configCenter: nacos://nacos.dubbo-system.svc:8848?username=nacos&password=nacos
          metadataReport: nacos://nacos.dubbo-system.svc:8848?username=nacos&password=nacos
    engine:
      id: default
      name: default
      type: kubernetes
      properties:
        podWatchSelector: metadata.namespace=dubbo-samples-shop
        dubboAppIdentifier:
          type: ByLabel
          labelKey: app
        dubboRPCPortIdentifier:
          type: ByLabel
          labelKey: org.apache.dubbo/dubbo-rpc-port
        dubboDiscoveryIdentifier:
          type: ByLabel
          labelKey: org.apache.dubbo/registry
        mainContainerChooseStrategy:
          type: ByIndex
          index: 0
---
apiVersion: v1
kind: Service
metadata:
  name: dubbo-admin
  namespace: dubbo-system
spec:
  type: ClusterIP
  selector:
    app: dubbo-admin
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dubbo-admin-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dubbo-admin
  namespace: dubbo-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dubbo-admin-cluster-binding
subjects:
  - kind: ServiceAccount
    name: dubbo-admin
    namespace: dubbo-system
roleRef:
  kind: ClusterRole
  name: dubbo-admin-cluster-role
  apiGroup: rbac.authorization.k8s.io
