language: java
sudo: false # faster builds

jdk:
    - openjdk8
    - openjdk11

cache:
  directories:
    - $HOME/.m2

install: true

script:
    - travis_wait 30 ./mvnw clean install -DskipTests=false -Dcheckstyle.skip=false -Drat.skip=false -Dmaven.javadoc.skip=true

after_success:
  - bash <(curl -s https://codecov.io/bash)
