language: java
sudo: false # faster builds

jdk:
    - oraclejdk8
    - oraclejdk11

before_install:
    - ./mvnw checkstyle:check

script:
    - travis_wait 30 ./mvnw clean package

after_success:
  - bash <(curl -s https://codecov.io/bash)
