{{- if .Values.serviceAccount.enabled }}
{{- $admin := . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "dubbo-admin.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- tpl (toYaml . | nindent 4) $admin }}
  {{- end }}
  name: {{ include "dubbo-admin.serviceAccountName" . }}
  namespace: {{ include "dubbo-admin.namespace" . }}
  {{- end }}
