# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "skywalking.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.ui.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "skywalking.ui.fullname" . }}
  {{- with .Values.ui.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ui.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range $cidr := .Values.ui.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
    {{- end }}
  {{- end }}
  type: {{ .Values.ui.service.type }}
  {{- if and (eq .Values.ui.service.type "ClusterIP") .Values.ui.service.clusterIP }}
  clusterIP: {{ .Values.ui.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.ui.service.externalPort }}
      targetPort: {{ .Values.ui.service.internalPort }}
      protocol: TCP
{{ if (and (eq .Values.ui.service.type "NodePort") (not (empty .Values.ui.service.nodePort))) }}
      nodePort: {{ .Values.ui.service.nodePort }}
{{ end }}
{{- if .Values.ui.service.portName }}
      name: {{ .Values.ui.service.portName }}
{{- end }}
{{- if .Values.ui.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.ui.service.externalIPs | indent 4 }}
{{- end }}
  selector:
    app: {{ template "skywalking.name" . }}
    component: "{{ .Values.ui.name }}"
    release: {{ .Release.Name }}
{{- if .Values.ui.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.ui.service.loadBalancerIP }}
{{- end }}
