version: '2'
services:
  dubbo-zookeeper:
    extends:
      file: zookeeper.yml
      service: dubbo-zookeeper
    networks:
      dubbo-net:
        aliases:
          - zookeeper
  dubbo-admin:
    image: xinmeng/dubbo-admin:2.0.0
    environment:
      - ZOOKEEPER=zookeeper:2181
      - ROOT_PASS=root
      - GUEST_PASS=guest
    ports:
      - 8090:7001
    networks:
      dubbo-net:
        aliases:
          - dubbo
networks:
    dubbo-net: