apiVersion: v2
appVersion: ""
name: dubbo-admin
description: Distributed application monitoring and management platform.
home: https://dubbo.apache.org
kubeVersion: '>=1.28.0-0'
maintainers:
  - name: dubbo
    email: dev@dubbo.apache.org
type: application
version: 0.5.0