/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by tools/resourcegen
// Run "make generate" to update this file.

// nolint:whitespace
package v1alpha1

import (
	systemproto "github.com/apache/dubbo-admin/api/system/v1alpha1"
	coremodel "github.com/apache/dubbo-admin/pkg/core/resource/model"
	"google.golang.org/protobuf/proto"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	k8sruntime "k8s.io/apimachinery/pkg/runtime"
)

// +kubebuilder:object:root=true
// +kubebuilder:resource:categories=dubbo,scope=Cluster

const ConfigKind coremodel.ResourceKind = "Config"

func init() {
	coremodel.RegisterResourceSchema(ConfigKind, NewConfigResource)
}

type ConfigResource struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Mesh is the name of the dubbo mesh this resource belongs to.
	// It may be omitted for cluster-scoped resources.
	//
	// +kubebuilder:validation:Optional
	Mesh string `json:"mesh,omitempty"`
	// Spec is the specification of the Dubbo Config resource.
	// +kubebuilder:validation:Optional
	Spec *systemproto.Config `json:"spec,omitempty"`
	// Status is the status of the Dubbo Config resource.
	Status ConfigResourceStatus `json:"status,omitempty"`
}

type ConfigResourceStatus struct {
	// define resource-specific status here
}

// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Namespaced
type ConfigResourceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ConfigResource `json:"items"`
}

func (r *ConfigResource) ResourceKind() coremodel.ResourceKind {
	return ConfigKind
}

func (r *ConfigResource) MeshName() string {
	return r.Mesh
}

func (r *ConfigResource) ResourceKey() string {
	return coremodel.BuildResourceKey(r.Mesh, r.Name)
}

func (r *ConfigResource) ResourceMeta() metav1.ObjectMeta {
	return r.ObjectMeta
}

func (r *ConfigResource) ResourceSpec() coremodel.ResourceSpec {
	return r.Spec
}
func (r *ConfigResource) DeepCopyObject() k8sruntime.Object {
	if r == nil {
		return nil
	}

	out := &ConfigResource{
		TypeMeta: r.TypeMeta,
		Mesh:     r.Mesh,
		Status:   r.Status,
	}

	r.ObjectMeta.DeepCopyInto(&out.ObjectMeta)

	if r.Spec != nil {
		out.Spec = proto.Clone(r.Spec).(*systemproto.Config)
	}

	return out
}

func NewConfigResourceWithAttributes(name string, mesh string) *ConfigResource {
	return &ConfigResource{
		TypeMeta: metav1.TypeMeta{
			Kind:       string(ConfigKind),
			APIVersion: "v1alpha1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:   name,
			Labels: map[string]string{},
		},
		Mesh: mesh,
	}
}

func NewConfigResource() coremodel.Resource {
	return &ConfigResource{
		TypeMeta: metav1.TypeMeta{
			Kind:       string(ConfigKind),
			APIVersion: "v1alpha1",
		},
	}
}
