# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $stsNoHeadlessSvcTypes := list "LoadBalancer" "NodePort" -}}
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.pushgateway.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus-pushgateway.defaultLabels" . | nindent 4 }}
    {{- with .Values.pushgateway.serviceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "prometheus-pushgateway.fullname" . }}
spec:
  {{- if .Values.pushgateway.service.clusterIP }}
  clusterIP: {{ .Values.pushgateway.service.clusterIP }}
  {{ else if and .Values.pushgateway.runAsStatefulSet (not (has .Values.pushgateway.service.type $stsNoHeadlessSvcTypes)) }}
  clusterIP: None # Headless service
  {{- end }}
  type: {{ .Values.pushgateway.service.type }}
  {{- with .Values.pushgateway.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- if .Values.pushgateway.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.pushgateway.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.pushgateway.service.port }}
      targetPort: {{ .Values.pushgateway.service.targetPort }}
      {{- if and (eq .Values.pushgateway.service.type "NodePort") .Values.pushgateway.service.nodePort }}
      nodePort: {{ .Values.pushgateway.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "prometheus-pushgateway.selectorLabels" . | nindent 4 }}
