// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: api/mesh/v1alpha1/condition_route.proto

package v1alpha1

import (
	_ "github.com/apache/dubbo-admin/api/mesh"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConditionRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion string                 `protobuf:"bytes,1,opt,name=configVersion,proto3" json:"configVersion,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Force         bool                   `protobuf:"varint,4,opt,name=force,proto3" json:"force,omitempty"`
	Runtime       bool                   `protobuf:"varint,5,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Key           string                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Scope         string                 `protobuf:"bytes,7,opt,name=scope,proto3" json:"scope,omitempty"`
	Conditions    []string               `protobuf:"bytes,8,rep,name=conditions,proto3" json:"conditions,omitempty"`
	// conditionRules preserves the structured v3.1 conditions. External YAML
	// still uses the field name `conditions`; the rule codec maps it by
	// configVersion so v3.0 and v3.1 never overwrite each other.
	ConditionRules []*ConditionRule `protobuf:"bytes,9,rep,name=conditionRules,proto3" json:"conditionRules,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConditionRoute) Reset() {
	*x = ConditionRoute{}
	mi := &file_api_mesh_v1alpha1_condition_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionRoute) ProtoMessage() {}

func (x *ConditionRoute) ProtoReflect() protoreflect.Message {
	mi := &file_api_mesh_v1alpha1_condition_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionRoute.ProtoReflect.Descriptor instead.
func (*ConditionRoute) Descriptor() ([]byte, []int) {
	return file_api_mesh_v1alpha1_condition_route_proto_rawDescGZIP(), []int{0}
}

func (x *ConditionRoute) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *ConditionRoute) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ConditionRoute) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ConditionRoute) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *ConditionRoute) GetRuntime() bool {
	if x != nil {
		return x.Runtime
	}
	return false
}

func (x *ConditionRoute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConditionRoute) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ConditionRoute) GetConditions() []string {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *ConditionRoute) GetConditionRules() []*ConditionRule {
	if x != nil {
		return x.ConditionRules
	}
	return nil
}

type ConditionRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *ConditionRuleFrom     `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            []*ConditionRuleTo     `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionRule) Reset() {
	*x = ConditionRule{}
	mi := &file_api_mesh_v1alpha1_condition_route_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionRule) ProtoMessage() {}

func (x *ConditionRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_mesh_v1alpha1_condition_route_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionRule.ProtoReflect.Descriptor instead.
func (*ConditionRule) Descriptor() ([]byte, []int) {
	return file_api_mesh_v1alpha1_condition_route_proto_rawDescGZIP(), []int{1}
}

func (x *ConditionRule) GetFrom() *ConditionRuleFrom {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ConditionRule) GetTo() []*ConditionRuleTo {
	if x != nil {
		return x.To
	}
	return nil
}

type ConditionRuleFrom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         string                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionRuleFrom) Reset() {
	*x = ConditionRuleFrom{}
	mi := &file_api_mesh_v1alpha1_condition_route_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionRuleFrom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionRuleFrom) ProtoMessage() {}

func (x *ConditionRuleFrom) ProtoReflect() protoreflect.Message {
	mi := &file_api_mesh_v1alpha1_condition_route_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionRuleFrom.ProtoReflect.Descriptor instead.
func (*ConditionRuleFrom) Descriptor() ([]byte, []int) {
	return file_api_mesh_v1alpha1_condition_route_proto_rawDescGZIP(), []int{2}
}

func (x *ConditionRuleFrom) GetMatch() string {
	if x != nil {
		return x.Match
	}
	return ""
}

type ConditionRuleTo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         string                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	Weight        int32                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"` // default value will be handled by application logic
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionRuleTo) Reset() {
	*x = ConditionRuleTo{}
	mi := &file_api_mesh_v1alpha1_condition_route_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionRuleTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionRuleTo) ProtoMessage() {}

func (x *ConditionRuleTo) ProtoReflect() protoreflect.Message {
	mi := &file_api_mesh_v1alpha1_condition_route_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionRuleTo.ProtoReflect.Descriptor instead.
func (*ConditionRuleTo) Descriptor() ([]byte, []int) {
	return file_api_mesh_v1alpha1_condition_route_proto_rawDescGZIP(), []int{3}
}

func (x *ConditionRuleTo) GetMatch() string {
	if x != nil {
		return x.Match
	}
	return ""
}

func (x *ConditionRuleTo) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

var File_api_mesh_v1alpha1_condition_route_proto protoreflect.FileDescriptor

const file_api_mesh_v1alpha1_condition_route_proto_rawDesc = "" +
	"\n" +
	"'api/mesh/v1alpha1/condition_route.proto\x12\x13dubbo.mesh.v1alpha1\x1a\x16api/mesh/options.proto\"\xdf\x02\n" +
	"\x0eConditionRoute\x12$\n" +
	"\rconfigVersion\x18\x01 \x01(\tR\rconfigVersion\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x14\n" +
	"\x05force\x18\x04 \x01(\bR\x05force\x12\x18\n" +
	"\aruntime\x18\x05 \x01(\bR\aruntime\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\x12\x14\n" +
	"\x05scope\x18\a \x01(\tR\x05scope\x12\x1e\n" +
	"\n" +
	"conditions\x18\b \x03(\tR\n" +
	"conditions\x12J\n" +
	"\x0econditionRules\x18\t \x03(\v2\".dubbo.mesh.v1alpha1.ConditionRuleR\x0econditionRules:-\xaa\x8c\x89\xa6\x01'\n" +
	"\x0eConditionRoute\x12\x0fConditionRoutes\x1a\x04mesh\"\x81\x01\n" +
	"\rConditionRule\x12:\n" +
	"\x04from\x18\x01 \x01(\v2&.dubbo.mesh.v1alpha1.ConditionRuleFromR\x04from\x124\n" +
	"\x02to\x18\x02 \x03(\v2$.dubbo.mesh.v1alpha1.ConditionRuleToR\x02to\")\n" +
	"\x11ConditionRuleFrom\x12\x14\n" +
	"\x05match\x18\x01 \x01(\tR\x05match\"?\n" +
	"\x0fConditionRuleTo\x12\x14\n" +
	"\x05match\x18\x01 \x01(\tR\x05match\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weightB1Z/github.com/apache/dubbo-admin/api/mesh/v1alpha1b\x06proto3"

var (
	file_api_mesh_v1alpha1_condition_route_proto_rawDescOnce sync.Once
	file_api_mesh_v1alpha1_condition_route_proto_rawDescData []byte
)

func file_api_mesh_v1alpha1_condition_route_proto_rawDescGZIP() []byte {
	file_api_mesh_v1alpha1_condition_route_proto_rawDescOnce.Do(func() {
		file_api_mesh_v1alpha1_condition_route_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_mesh_v1alpha1_condition_route_proto_rawDesc), len(file_api_mesh_v1alpha1_condition_route_proto_rawDesc)))
	})
	return file_api_mesh_v1alpha1_condition_route_proto_rawDescData
}

var file_api_mesh_v1alpha1_condition_route_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_mesh_v1alpha1_condition_route_proto_goTypes = []any{
	(*ConditionRoute)(nil),    // 0: dubbo.mesh.v1alpha1.ConditionRoute
	(*ConditionRule)(nil),     // 1: dubbo.mesh.v1alpha1.ConditionRule
	(*ConditionRuleFrom)(nil), // 2: dubbo.mesh.v1alpha1.ConditionRuleFrom
	(*ConditionRuleTo)(nil),   // 3: dubbo.mesh.v1alpha1.ConditionRuleTo
}
var file_api_mesh_v1alpha1_condition_route_proto_depIdxs = []int32{
	1, // 0: dubbo.mesh.v1alpha1.ConditionRoute.conditionRules:type_name -> dubbo.mesh.v1alpha1.ConditionRule
	2, // 1: dubbo.mesh.v1alpha1.ConditionRule.from:type_name -> dubbo.mesh.v1alpha1.ConditionRuleFrom
	3, // 2: dubbo.mesh.v1alpha1.ConditionRule.to:type_name -> dubbo.mesh.v1alpha1.ConditionRuleTo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_mesh_v1alpha1_condition_route_proto_init() }
func file_api_mesh_v1alpha1_condition_route_proto_init() {
	if File_api_mesh_v1alpha1_condition_route_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_mesh_v1alpha1_condition_route_proto_rawDesc), len(file_api_mesh_v1alpha1_condition_route_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_mesh_v1alpha1_condition_route_proto_goTypes,
		DependencyIndexes: file_api_mesh_v1alpha1_condition_route_proto_depIdxs,
		MessageInfos:      file_api_mesh_v1alpha1_condition_route_proto_msgTypes,
	}.Build()
	File_api_mesh_v1alpha1_condition_route_proto = out.File
	file_api_mesh_v1alpha1_condition_route_proto_goTypes = nil
	file_api_mesh_v1alpha1_condition_route_proto_depIdxs = nil
}
