//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/mesh/v1alpha1/rule_intent.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RuleIntent records a pending rule mutation before the resource write.
// The committed RuleVersion is created from observed or repaired rule state.
type RuleIntent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent rule identification
	ParentRuleKind string `protobuf:"bytes,1,opt,name=parent_rule_kind,json=parentRuleKind,proto3" json:"parent_rule_kind,omitempty"`
	ParentRuleMesh string `protobuf:"bytes,2,opt,name=parent_rule_mesh,json=parentRuleMesh,proto3" json:"parent_rule_mesh,omitempty"`
	ParentRuleName string `protobuf:"bytes,3,opt,name=parent_rule_name,json=parentRuleName,proto3" json:"parent_rule_name,omitempty"`
	// Intent metadata
	ContentHash string `protobuf:"bytes,5,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"` // Hash of the intended spec
	SpecJson    string `protobuf:"bytes,6,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"`          // Snapshot of intended spec
	Operation   string `protobuf:"bytes,7,opt,name=operation,proto3" json:"operation,omitempty"`                        // CREATE, UPDATE, DELETE
	Source      string `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`                              // ADMIN, UPSTREAM, BOOTSTRAP, ROLLBACK
	Author      string `protobuf:"bytes,9,opt,name=author,proto3" json:"author,omitempty"`                              // Who initiated this change
	Reason      string `protobuf:"bytes,10,opt,name=reason,proto3" json:"reason,omitempty"`                             // Why this change was made
	// rolled_back_from_id records the historical version whose snapshot is being
	// re-published. It is audit metadata only and never a current-version pointer.
	RolledBackFromId int64 `protobuf:"varint,11,opt,name=rolled_back_from_id,json=rolledBackFromId,proto3" json:"rolled_back_from_id,omitempty"`
	// Intent lifecycle
	Status        string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`                                    // PENDING, APPLIED, FAILED, COMMITTED
	FailureReason string                 `protobuf:"bytes,13,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"` // Error message if status=FAILED
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AppliedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`
	CommittedAt   *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=committed_at,json=committedAt,proto3" json:"committed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleIntent) Reset() {
	*x = RuleIntent{}
	mi := &file_api_mesh_v1alpha1_rule_intent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleIntent) ProtoMessage() {}

func (x *RuleIntent) ProtoReflect() protoreflect.Message {
	mi := &file_api_mesh_v1alpha1_rule_intent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleIntent.ProtoReflect.Descriptor instead.
func (*RuleIntent) Descriptor() ([]byte, []int) {
	return file_api_mesh_v1alpha1_rule_intent_proto_rawDescGZIP(), []int{0}
}

func (x *RuleIntent) GetParentRuleKind() string {
	if x != nil {
		return x.ParentRuleKind
	}
	return ""
}

func (x *RuleIntent) GetParentRuleMesh() string {
	if x != nil {
		return x.ParentRuleMesh
	}
	return ""
}

func (x *RuleIntent) GetParentRuleName() string {
	if x != nil {
		return x.ParentRuleName
	}
	return ""
}

func (x *RuleIntent) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *RuleIntent) GetSpecJson() string {
	if x != nil {
		return x.SpecJson
	}
	return ""
}

func (x *RuleIntent) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *RuleIntent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RuleIntent) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *RuleIntent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RuleIntent) GetRolledBackFromId() int64 {
	if x != nil {
		return x.RolledBackFromId
	}
	return 0
}

func (x *RuleIntent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RuleIntent) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *RuleIntent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RuleIntent) GetAppliedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AppliedAt
	}
	return nil
}

func (x *RuleIntent) GetCommittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CommittedAt
	}
	return nil
}

// RuleMeta tracks the current committed version for a rule. Rollback advances
// current_version_id to the new rollback version, not to rolled_back_from_id.
type RuleMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent rule identification
	ParentRuleKind string `protobuf:"bytes,1,opt,name=parent_rule_kind,json=parentRuleKind,proto3" json:"parent_rule_kind,omitempty"`
	ParentRuleMesh string `protobuf:"bytes,2,opt,name=parent_rule_mesh,json=parentRuleMesh,proto3" json:"parent_rule_mesh,omitempty"`
	ParentRuleName string `protobuf:"bytes,3,opt,name=parent_rule_name,json=parentRuleName,proto3" json:"parent_rule_name,omitempty"`
	// Current state
	CurrentVersionId   int64                  `protobuf:"varint,4,opt,name=current_version_id,json=currentVersionId,proto3" json:"current_version_id,omitempty"`      // ID of the current committed version
	CurrentVersionNo   int64                  `protobuf:"varint,5,opt,name=current_version_no,json=currentVersionNo,proto3" json:"current_version_no,omitempty"`      // Version number of current version
	CurrentContentHash string                 `protobuf:"bytes,6,opt,name=current_content_hash,json=currentContentHash,proto3" json:"current_content_hash,omitempty"` // Hash of current spec
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RuleMeta) Reset() {
	*x = RuleMeta{}
	mi := &file_api_mesh_v1alpha1_rule_intent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleMeta) ProtoMessage() {}

func (x *RuleMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_mesh_v1alpha1_rule_intent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleMeta.ProtoReflect.Descriptor instead.
func (*RuleMeta) Descriptor() ([]byte, []int) {
	return file_api_mesh_v1alpha1_rule_intent_proto_rawDescGZIP(), []int{1}
}

func (x *RuleMeta) GetParentRuleKind() string {
	if x != nil {
		return x.ParentRuleKind
	}
	return ""
}

func (x *RuleMeta) GetParentRuleMesh() string {
	if x != nil {
		return x.ParentRuleMesh
	}
	return ""
}

func (x *RuleMeta) GetParentRuleName() string {
	if x != nil {
		return x.ParentRuleName
	}
	return ""
}

func (x *RuleMeta) GetCurrentVersionId() int64 {
	if x != nil {
		return x.CurrentVersionId
	}
	return 0
}

func (x *RuleMeta) GetCurrentVersionNo() int64 {
	if x != nil {
		return x.CurrentVersionNo
	}
	return 0
}

func (x *RuleMeta) GetCurrentContentHash() string {
	if x != nil {
		return x.CurrentContentHash
	}
	return ""
}

func (x *RuleMeta) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_mesh_v1alpha1_rule_intent_proto protoreflect.FileDescriptor

const file_api_mesh_v1alpha1_rule_intent_proto_rawDesc = "" +
	"\n" +
	"#api/mesh/v1alpha1/rule_intent.proto\x12\x13dubbo.mesh.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe5\x04\n" +
	"\n" +
	"RuleIntent\x12(\n" +
	"\x10parent_rule_kind\x18\x01 \x01(\tR\x0eparentRuleKind\x12(\n" +
	"\x10parent_rule_mesh\x18\x02 \x01(\tR\x0eparentRuleMesh\x12(\n" +
	"\x10parent_rule_name\x18\x03 \x01(\tR\x0eparentRuleName\x12!\n" +
	"\fcontent_hash\x18\x05 \x01(\tR\vcontentHash\x12\x1b\n" +
	"\tspec_json\x18\x06 \x01(\tR\bspecJson\x12\x1c\n" +
	"\toperation\x18\a \x01(\tR\toperation\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\x12\x16\n" +
	"\x06author\x18\t \x01(\tR\x06author\x12\x16\n" +
	"\x06reason\x18\n" +
	" \x01(\tR\x06reason\x12-\n" +
	"\x13rolled_back_from_id\x18\v \x01(\x03R\x10rolledBackFromId\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12%\n" +
	"\x0efailure_reason\x18\r \x01(\tR\rfailureReason\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"applied_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tappliedAt\x12=\n" +
	"\fcommitted_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\vcommittedAtJ\x04\b\x04\x10\x05R\n" +
	"version_no\"\xd1\x02\n" +
	"\bRuleMeta\x12(\n" +
	"\x10parent_rule_kind\x18\x01 \x01(\tR\x0eparentRuleKind\x12(\n" +
	"\x10parent_rule_mesh\x18\x02 \x01(\tR\x0eparentRuleMesh\x12(\n" +
	"\x10parent_rule_name\x18\x03 \x01(\tR\x0eparentRuleName\x12,\n" +
	"\x12current_version_id\x18\x04 \x01(\x03R\x10currentVersionId\x12,\n" +
	"\x12current_version_no\x18\x05 \x01(\x03R\x10currentVersionNo\x120\n" +
	"\x14current_content_hash\x18\x06 \x01(\tR\x12currentContentHash\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB1Z/github.com/apache/dubbo-admin/api/mesh/v1alpha1b\x06proto3"

var (
	file_api_mesh_v1alpha1_rule_intent_proto_rawDescOnce sync.Once
	file_api_mesh_v1alpha1_rule_intent_proto_rawDescData []byte
)

func file_api_mesh_v1alpha1_rule_intent_proto_rawDescGZIP() []byte {
	file_api_mesh_v1alpha1_rule_intent_proto_rawDescOnce.Do(func() {
		file_api_mesh_v1alpha1_rule_intent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_mesh_v1alpha1_rule_intent_proto_rawDesc), len(file_api_mesh_v1alpha1_rule_intent_proto_rawDesc)))
	})
	return file_api_mesh_v1alpha1_rule_intent_proto_rawDescData
}

var file_api_mesh_v1alpha1_rule_intent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_mesh_v1alpha1_rule_intent_proto_goTypes = []any{
	(*RuleIntent)(nil),            // 0: dubbo.mesh.v1alpha1.RuleIntent
	(*RuleMeta)(nil),              // 1: dubbo.mesh.v1alpha1.RuleMeta
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_mesh_v1alpha1_rule_intent_proto_depIdxs = []int32{
	2, // 0: dubbo.mesh.v1alpha1.RuleIntent.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: dubbo.mesh.v1alpha1.RuleIntent.applied_at:type_name -> google.protobuf.Timestamp
	2, // 2: dubbo.mesh.v1alpha1.RuleIntent.committed_at:type_name -> google.protobuf.Timestamp
	2, // 3: dubbo.mesh.v1alpha1.RuleMeta.updated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_mesh_v1alpha1_rule_intent_proto_init() }
func file_api_mesh_v1alpha1_rule_intent_proto_init() {
	if File_api_mesh_v1alpha1_rule_intent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_mesh_v1alpha1_rule_intent_proto_rawDesc), len(file_api_mesh_v1alpha1_rule_intent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_mesh_v1alpha1_rule_intent_proto_goTypes,
		DependencyIndexes: file_api_mesh_v1alpha1_rule_intent_proto_depIdxs,
		MessageInfos:      file_api_mesh_v1alpha1_rule_intent_proto_msgTypes,
	}.Build()
	File_api_mesh_v1alpha1_rule_intent_proto = out.File
	file_api_mesh_v1alpha1_rule_intent_proto_goTypes = nil
	file_api_mesh_v1alpha1_rule_intent_proto_depIdxs = nil
}
