syntax = "proto3";

package dubbo.mesh.v1alpha1;

option go_package = "github.com/apache/dubbo-admin/api/mesh/v1alpha1";

import "api/mesh/options.proto";

// RuntimeInstance is retrieved from Engine, defines the attributes of instance in runtime environments
message RuntimeInstance {
  option (dubbo.mesh.resource).name = "RuntimeInstance";
  option (dubbo.mesh.resource).plural_name = "RuntimeInstances";
  option (dubbo.mesh.resource).package = "mesh";
  option (dubbo.mesh.resource).is_experimental = true;

  string name = 1;

  string ip = 2;

  string image = 3;

  string appName = 4;

  string createTime = 5;

  string startTime = 6;

  string readyTime = 7;

  string phase = 8;

  string workloadName = 9;

  string workloadType = 10;

  string node = 11;

  repeated Probe probes = 12;

  repeated Condition conditions = 13;
}

message Probe {
  string type = 1;
  int32 port = 2;
}

// reference: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-conditions
message Condition{

  string type = 1;

  string status = 2;

  string lastTransitionTime = 3;

  string reason = 4;

  string message = 5;
}