// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: api/mesh/v1alpha1/script_route.proto

package v1alpha1

import (
	_ "github.com/apache/dubbo-admin/api/mesh"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScriptRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion string                 `protobuf:"bytes,1,opt,name=configVersion,proto3" json:"configVersion,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Script        string                 `protobuf:"bytes,6,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptRoute) Reset() {
	*x = ScriptRoute{}
	mi := &file_api_mesh_v1alpha1_script_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptRoute) ProtoMessage() {}

func (x *ScriptRoute) ProtoReflect() protoreflect.Message {
	mi := &file_api_mesh_v1alpha1_script_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptRoute.ProtoReflect.Descriptor instead.
func (*ScriptRoute) Descriptor() ([]byte, []int) {
	return file_api_mesh_v1alpha1_script_route_proto_rawDescGZIP(), []int{0}
}

func (x *ScriptRoute) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *ScriptRoute) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ScriptRoute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ScriptRoute) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ScriptRoute) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScriptRoute) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

var File_api_mesh_v1alpha1_script_route_proto protoreflect.FileDescriptor

const file_api_mesh_v1alpha1_script_route_proto_rawDesc = "" +
	"\n" +
	"$api/mesh/v1alpha1/script_route.proto\x12\x13dubbo.mesh.v1alpha1\x1a\x16api/mesh/options.proto\"\xca\x01\n" +
	"\vScriptRoute\x12$\n" +
	"\rconfigVersion\x18\x01 \x01(\tR\rconfigVersion\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x16\n" +
	"\x06script\x18\x06 \x01(\tR\x06script:'\xaa\x8c\x89\xa6\x01!\n" +
	"\vScriptRoute\x12\fScriptRoutes\x1a\x04meshB1Z/github.com/apache/dubbo-admin/api/mesh/v1alpha1b\x06proto3"

var (
	file_api_mesh_v1alpha1_script_route_proto_rawDescOnce sync.Once
	file_api_mesh_v1alpha1_script_route_proto_rawDescData []byte
)

func file_api_mesh_v1alpha1_script_route_proto_rawDescGZIP() []byte {
	file_api_mesh_v1alpha1_script_route_proto_rawDescOnce.Do(func() {
		file_api_mesh_v1alpha1_script_route_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_mesh_v1alpha1_script_route_proto_rawDesc), len(file_api_mesh_v1alpha1_script_route_proto_rawDesc)))
	})
	return file_api_mesh_v1alpha1_script_route_proto_rawDescData
}

var file_api_mesh_v1alpha1_script_route_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_mesh_v1alpha1_script_route_proto_goTypes = []any{
	(*ScriptRoute)(nil), // 0: dubbo.mesh.v1alpha1.ScriptRoute
}
var file_api_mesh_v1alpha1_script_route_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_mesh_v1alpha1_script_route_proto_init() }
func file_api_mesh_v1alpha1_script_route_proto_init() {
	if File_api_mesh_v1alpha1_script_route_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_mesh_v1alpha1_script_route_proto_rawDesc), len(file_api_mesh_v1alpha1_script_route_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_mesh_v1alpha1_script_route_proto_goTypes,
		DependencyIndexes: file_api_mesh_v1alpha1_script_route_proto_depIdxs,
		MessageInfos:      file_api_mesh_v1alpha1_script_route_proto_msgTypes,
	}.Build()
	File_api_mesh_v1alpha1_script_route_proto = out.File
	file_api_mesh_v1alpha1_script_route_proto_goTypes = nil
	file_api_mesh_v1alpha1_script_route_proto_depIdxs = nil
}
