syntax = "proto3";

package dubbo.mesh.v1alpha1;

option go_package = "github.com/apache/dubbo-admin/api/mesh/v1alpha1";

import "api/mesh/options.proto";


message Service{
  option (dubbo.mesh.resource).name = "ServiceResource";
  option (dubbo.mesh.resource).type = "Service";
  option (dubbo.mesh.resource).package = "mesh";
  option (dubbo.mesh.resource).ws.name = "service";
  option (dubbo.mesh.resource).ws.plural = "services";
  option (dubbo.mesh.resource).ws.read_only = true;
  option (dubbo.mesh.resource).scope_namespace = true;
  option (dubbo.mesh.resource).allow_to_inspect = true;

  string name = 1;

  string group = 2;

  string version = 3;

  string language = 4;

  repeated string providers = 5;

  repeated string consumers = 6;

  map<string, string> features = 99;
}