syntax = "proto3";

package dubbo.mesh.v1alpha1;

option go_package = "github.com/apache/dubbo-admin/api/mesh/v1alpha1";

import "api/mesh/options.proto";

message ServiceProviderMetadata {
  option (dubbo.mesh.resource).name = "ServiceProviderMetadata";
  option (dubbo.mesh.resource).plural_name = "ServiceProviderMetaDatas";
  option (dubbo.mesh.resource).package = "mesh";
  option (dubbo.mesh.resource).is_experimental = false;

  string serviceName = 1;

  string providerAppName = 2;

  string version = 3;

  string group = 4;
  // TODO add more fields
}