apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: default
spec:
  selector:
    app: nacos
  ports:
    - name: http
      port: 8848
      targetPort: 8848
    - name: client-rpc
      port: 9848
      targetPort: 9848
    - name: raft-rpc
      port: 9849
      targetPort: 9849
    - name: old-raft-rpc
      port: 7848
      targetPort: 7848