apiVersion: v2
appVersion: "1.0"
name: nacos
description: an easy-to-use dynamic service discovery, configuration and service management platform for building cloud native applications.
home: https://nacos.io
kubeVersion: '>=1.20.0-0'
maintainers:
  - email: dev@dubbo.apache.org
    name: dubbo
sources:
  - https://github.com/alibaba/nacos
type: application
version: 0.1.5
