syntax = "proto3";

package dubbo.mesh;

option go_package = "github.com/apache/dubbo-admin/api/mesh";

import "google/protobuf/descriptor.proto";

message DubboResourceOptions {
  // Name and type of the dubbo resource struct.
  string name = 1;

  // The name of the resource showed as plural
  string plural_name = 2;

  // Name of the resource's Go package.
  string package = 3;

  // Is Experimental indicates if a resource is in experimental state.
  bool is_experimental = 4;
}

extend google.protobuf.MessageOptions {
  DubboResourceOptions resource = 43534533; // 'dubbo'
}
