{
 "title": "Dubbo可观测性面板",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "application_name", "label": "application_name", "query": { "query": "dubbo_provider_rt_seconds_p99" } }
  ]
 },
 "panels": [
  {
   "title": "Dubbo Stat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "application_name",
     "type": "text",
     "description": "application_name",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
     "options": {
      "content": "<div style=\"text-align:center;font-size:30px\">${application_name}</div>"
     },
     "targets": [
      {
       "expr": "qps{application_name=\"$application_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "provider_success_rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(dubbo_provider_requests_succeed_total{application_name=\"$application_name\"}) / sum(dubbo_provider_requests_total{application_name=\"$application_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "provider_failed_rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(dubbo_provider_requests_failed_total{application_name=\"$application_name\"}) OR on() vector(0)  / sum(dubbo_provider_requests_total{application_name=\"$application_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "provider_error_total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(dubbo_provider_requests_failed_total{application_name=\"$application_name\"}) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "timeout_total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(dubbo_provider_requests_timeout_total{application_name=\"$application_name\"}) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "limit_total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(dubbo_provider_requests_limit_total{application_name=\"$application_name\"}) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "unknown_total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(dubbo_provider_requests_unknown_total{application_name=\"$application_name\"})OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "rt_max",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(dubbo_provider_rt_seconds_max{application_name=\"$application_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "rt_min",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(dubbo_provider_rt_seconds_min{application_name=\"$application_name\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Provider Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "provider_qps",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "dubbo_provider_qps_seconds{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_requests_total(2m)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(dubbo_provider_requests_total{application_name=\"$application_name\"}[2m])",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_requests_processing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "dubbo_provider_requests_processing{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_requests_succeed(2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(dubbo_provider_requests_succeed_total{application_name=\"$application_name\"}[2m])",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_requests_total_aggregate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "dubbo_provider_requests_total_aggregate{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_requests_succeed_aggregate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "dubbo_provider_requests_succeed_aggregate{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Provider RT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "provider_rt_sum(1m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 23, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(dubbo_provider_rt_seconds_sum{application_name=\"$application_name\"}[1m])",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_rt_min",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dubbo_provider_rt_seconds_min{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_rt_max",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dubbo_provider_rt_seconds_max{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_rt_avg ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dubbo_provider_rt_seconds_avg{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_rt_last",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dubbo_provider_rt_seconds_last{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": " provider_rt_p95",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dubbo_provider_rt_seconds_p95{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_rt_p99",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dubbo_provider_rt_seconds_p99{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Provider Error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "provider_requests_failed_total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "dubbo_provider_requests_failed_total{application_name=\"$application_name\"} OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_requests_limit",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "dubbo_provider_requests_limit_total{application_name=\"$application_name\"} OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_requests_business_failed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "dubbo_provider_requests_business_failed_total{application_name=\"$application_name\"} OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_requests_unknown_failed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "dubbo_provider_requests_unknown_failed_total{application_name=\"$application_name\"}OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_requests_timeout",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "dubbo_provider_requests_timeout_total{application_name=\"$application_name\"} OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "consumer_qps",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "dubbo_consumer_qps_seconds{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_request_total(2m)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(dubbo_consumer_requests_total{application_name=\"$application_name\"}[2m])",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_requests_processing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "dubbo_consumer_requests_processing{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_requests_succeed(2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(dubbo_consumer_requests_succeed_total{application_name=\"$application_name\"}[2m])",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_requests_total_aggregate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "dubbo_consumer_requests_total_aggregate{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_requests_succeed_aggregate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "expr": "dubbo_consumer_requests_succeed_aggregate{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer RT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "consumer_rt_sum(1m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 23, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(dubbo_consumer_rt_seconds_sum{application_name=\"$application_name\"}[1m])",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_rt_min",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dubbo_provider_rt_seconds_min{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_rt_max",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dubbo_consumer_rt_seconds_max{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_rt_avg ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dubbo_consumer_rt_seconds_avg{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_rt_last",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dubbo_consumer_rt_seconds_last{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": " provider_rt_p95",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dubbo_consumer_rt_seconds_p95{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_rt_p99",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dubbo_consumer_rt_seconds_p99{application_name=\"$application_name\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "consumer_requests_failed_total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "dubbo_consumer_requests_failed_total{application_name=\"$application_name\"} OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_requests_limit",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "dubbo_consumer_requests_limit_total{application_name=\"$application_name\"} OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_requests_business_failed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "dubbo_consumer_requests_business_failed_total{application_name=\"$application_name\"} OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_requests_unknown_failed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "dubbo_consumer_requests_unknown_failed_total{application_name=\"$application_name\"}OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_requests_timeout",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "dubbo_consumer_requests_timeout_total{application_name=\"$application_name\"} OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "注册中心",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "配置中心",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "元数据中心",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ]
  }
 ]
}