{{- if .Values.envSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dubbo-admin.fullname" . }}-env
  namespace: {{ include "dubbo-admin.namespace" . }}
  labels:
    {{- include "dubbo-admin.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.envSecret }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}