apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ include "dubbo-admin.namespace" . }}
  labels:
    {{- include "dubbo-admin.labels" . | nindent 4 }}
  type: Opaque
data:
  application.properties: {{ tpl (toYaml .Values.properties) . | b64enc }}
