/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by tools/resourcegen
// Run "make generate" to update this file.

// nolint:whitespace
package v1alpha1

import (
	"google.golang.org/protobuf/proto"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	k8sruntime "k8s.io/apimachinery/pkg/runtime"

	meshproto "github.com/apache/dubbo-admin/api/mesh/v1alpha1"
	"github.com/apache/dubbo-admin/pkg/core/logger"
	coremodel "github.com/apache/dubbo-admin/pkg/core/resource/model"
)

const InstanceKind coremodel.ResourceKind = "Instance"

func init() {
	coremodel.RegisterResourceSchema(InstanceKind, NewInstanceResource)
}

type InstanceResource struct {
	metav1.TypeMeta `json:",inline"`

	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Mesh is the name of the dubbo mesh this resource belongs to.
	// It may be omitted for cluster-scoped resources.
	Mesh string `json:"mesh,omitempty"`

	// Spec is the specification of the Dubbo Instance resource.
	Spec *meshproto.Instance `json:"spec,omitempty"`

	// Status is the status of the Dubbo Instance resource.
	Status InstanceResourceStatus `json:"status,omitempty"`
}

type InstanceResourceStatus struct {
	// define resource-specific status here
}

type InstanceResourceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InstanceResource `json:"items"`
}

func (r *InstanceResource) ResourceKind() coremodel.ResourceKind {
	return InstanceKind
}

func (r *InstanceResource) MeshName() string {
	return r.Mesh
}

func (r *InstanceResource) ResourceKey() string {
	return coremodel.BuildResourceKey(r.Mesh, r.Name)
}

func (r *InstanceResource) ResourceMeta() metav1.ObjectMeta {
	return r.ObjectMeta
}

func (r *InstanceResource) ResourceSpec() coremodel.ResourceSpec {
	return r.Spec
}
func (r *InstanceResource) DeepCopyObject() k8sruntime.Object {
	if r == nil {
		return nil
	}

	out := &InstanceResource{
		TypeMeta: r.TypeMeta,
		Mesh:     r.Mesh,
		Status:   r.Status,
	}

	r.ObjectMeta.DeepCopyInto(&out.ObjectMeta)

	if r.Spec != nil {
		spec, ok := proto.Clone(r.Spec).(*meshproto.Instance)
		if !ok {
			logger.Warnf("failed to clone spec %v, spec is not conformed to %s", r.Spec, r.ResourceKind())
			return out
		}
		out.Spec = spec
	}

	return out
}

func NewInstanceResourceWithAttributes(name string, mesh string) *InstanceResource {
	return &InstanceResource{
		TypeMeta: metav1.TypeMeta{
			Kind:       string(InstanceKind),
			APIVersion: "v1alpha1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:   name,
			Labels: map[string]string{},
		},
		Mesh: mesh,
	}
}

func NewInstanceResource() coremodel.Resource {
	return &InstanceResource{
		TypeMeta: metav1.TypeMeta{
			Kind:       string(InstanceKind),
			APIVersion: "v1alpha1",
		},
	}
}
