/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by tools/resourcegen
// Run "make generate" to update this file.

// nolint:whitespace
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	meshproto "github.com/apache/dubbo-admin/api/mesh/v1alpha1"
	coremodel "github.com/apache/dubbo-admin/pkg/core/resource/model"
)

// +kubebuilder:object:root=true
// +kubebuilder:resource:categories=dubbo,scope=Cluster

const TagRouteKind coremodel.ResourceKind = "TagRoute"

func init() {
	coremodel.RegisterResourceKind(TagRouteKind)
}

type TagRouteResource struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Mesh is the name of the dubbo mesh this resource belongs to.
	// It may be omitted for cluster-scoped resources.
	//
	// +kubebuilder:validation:Optional
	Mesh string `json:"mesh,omitempty"`
	// Spec is the specification of the Dubbo TagRoute resource.
	// +kubebuilder:validation:Optional
	Spec *meshproto.TagRoute `json:"spec,omitempty"`
	// Status is the status of the Dubbo TagRoute resource.
	Status TagRouteResourceStatus `json:"status,omitempty"`
}

type TagRouteResourceStatus struct {
	// define resource-specific status here
}

// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Namespaced
type TagRouteResourceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TagRouteResource `json:"items"`
}

func (r *TagRouteResource) ResourceKind() coremodel.ResourceKind {
	return TagRouteKind
}

func (r *TagRouteResource) MeshName() string {
	return r.Mesh
}

func (r *TagRouteResource) ResourceKey() string {
	return coremodel.BuildResourceKey(r.Mesh, r.Name)
}

func (r *TagRouteResource) ResourceMeta() metav1.ObjectMeta {
	return r.ObjectMeta
}

func (r *TagRouteResource) ResourceSpec() coremodel.ResourceSpec {
	return r.Spec
}

func NewTagRouteResource(name string, mesh string, apiVersion string) *TagRouteResource {
	return &TagRouteResource{
		TypeMeta: metav1.TypeMeta{
			Kind:       string(TagRouteKind),
			APIVersion: apiVersion,
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:   name,
			Labels: map[string]string{},
		},
		Mesh: mesh,
	}
}
