/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by tools/resourcegen
// Run "make generate" to update this file.

// nolint:whitespace
package v1alpha1

import (
	"encoding/json"

	"google.golang.org/protobuf/proto"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	k8sruntime "k8s.io/apimachinery/pkg/runtime"

	meshproto "github.com/apache/dubbo-admin/api/mesh/v1alpha1"
	"github.com/apache/dubbo-admin/pkg/core/logger"
	coremodel "github.com/apache/dubbo-admin/pkg/core/resource/model"
)

const ZKConfigKind coremodel.ResourceKind = "ZKConfig"

func init() {
	coremodel.RegisterResourceSchema(ZKConfigKind, NewZKConfigResource, NewZKConfigResourceList)
}

type ZKConfigResource struct {
	metav1.TypeMeta `json:",inline"`

	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Mesh is the name of the dubbo mesh this resource belongs to.
	// It may be omitted for cluster-scoped resources.
	Mesh string `json:"mesh,omitempty"`

	// Spec is the specification of the Dubbo ZKConfig resource.
	Spec *meshproto.ZKConfig `json:"spec,omitempty"`

	// Status is the status of the Dubbo ZKConfig resource.
	Status ZKConfigResourceStatus `json:"status,omitempty"`
}

type ZKConfigResourceStatus struct {
	// define resource-specific status here
}

func (r *ZKConfigResource) ResourceKind() coremodel.ResourceKind {
	return ZKConfigKind
}

func (r *ZKConfigResource) ResourceMesh() string {
	return r.Mesh
}

func (r *ZKConfigResource) ResourceKey() string {
	return coremodel.BuildResourceKey(r.Mesh, r.Name)
}

func (r *ZKConfigResource) ResourceMeta() metav1.ObjectMeta {
	return r.ObjectMeta
}

func (r *ZKConfigResource) ResourceSpec() coremodel.ResourceSpec {
	return r.Spec
}

func (r *ZKConfigResource) DeepCopyObject() k8sruntime.Object {
	out := &ZKConfigResource{
		TypeMeta: r.TypeMeta,
		Mesh:     r.Mesh,
		Status:   r.Status,
	}

	r.ObjectMeta.DeepCopyInto(&out.ObjectMeta)

	if r.Spec != nil {
		spec, ok := proto.Clone(r.Spec).(*meshproto.ZKConfig)
		if !ok {
			logger.Warnf("failed to clone spec %v, spec is not conformed to %s", r.Spec, r.ResourceKind())
			return out
		}
		out.Spec = spec
	}

	return out
}

func (r *ZKConfigResource) String() string {
	jsonStr, err := json.Marshal(r)
	if err != nil {
		logger.Errorf("failed to encode ZKConfigResource: %s to json, err: %v", r.ResourceKey(), err)
		return ""
	}
	return string(jsonStr)
}

func NewZKConfigResourceWithAttributes(name string, mesh string) *ZKConfigResource {
	return &ZKConfigResource{
		TypeMeta: metav1.TypeMeta{
			Kind:       string(ZKConfigKind),
			APIVersion: "v1alpha1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:   name,
			Labels: map[string]string{},
		},
		Mesh: mesh,
		Spec: &meshproto.ZKConfig{},
	}
}

func NewZKConfigResource() coremodel.Resource {
	return &ZKConfigResource{
		TypeMeta: metav1.TypeMeta{
			Kind:       string(ZKConfigKind),
			APIVersion: "v1alpha1",
		},
		Spec: &meshproto.ZKConfig{},
	}
}

type ZKConfigResourceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []*ZKConfigResource `json:"items"`
}

func (r *ZKConfigResourceList) DeepCopyObject() k8sruntime.Object {
	out := &ZKConfigResourceList{
		TypeMeta: r.TypeMeta,
	}
	r.ListMeta.DeepCopyInto(&out.ListMeta)

	if len(r.Items) == 0 {
		return out
	}
	out.Items = make([]*ZKConfigResource, len(r.Items))
	for i := range r.Items {
		out.Items[i] = r.Items[i].DeepCopyObject().(*ZKConfigResource)
	}
	return out
}

func NewZKConfigResourceList() coremodel.ResourceList {
	return &ZKConfigResourceList{
		TypeMeta: metav1.TypeMeta{
			Kind:       string(ZKConfigKind),
			APIVersion: "v1alpha1",
		},
		Items: make([]*ZKConfigResource, 0),
	}
}

func (r *ZKConfigResourceList) SetItems(items []coremodel.Resource) {
	r.Items = make([]*ZKConfigResource, len(items))
	for i := range items {
		res, ok := items[i].(*ZKConfigResource)
		if !ok {
			logger.Errorf("unexpected resource type, expected: %s, get %s", ZKConfigKind, res.ResourceKind())
			continue
		}
		r.Items[i] = res
	}
}

func NewZKConfigResourceListWithItems(items ...*ZKConfigResource) *ZKConfigResourceList {
	return &ZKConfigResourceList{
		TypeMeta: metav1.TypeMeta{
			Kind:       string(ZKConfigKind),
			APIVersion: "v1alpha1",
		},
		Items: items,
	}
}
