{{- if .Values.prometheus.monitor.enabled }}
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "kube-state-metrics.fullname" . }}
  namespace: {{ template "kube-state-metrics.namespace" . }}
  labels:
    {{- include "kube-state-metrics.labels" . | indent 4 }}
  {{- with .Values.prometheus.monitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ default "app.kubernetes.io/name" .Values.prometheus.monitor.jobLabel }}
  {{- with .Values.prometheus.monitor.targetLabels }}
  targetLabels:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  {{- with .Values.prometheus.monitor.podTargetLabels }}
  podTargetLabels:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  {{- include "servicemonitor.scrapeLimits" .Values.prometheus.monitor | indent 2 }}
  selector:
    matchLabels:
    {{- with .Values.prometheus.monitor.selectorOverride }}
      {{- toYaml . | nindent 6 }}
    {{- else }}
      {{- include "kube-state-metrics.selectorLabels" . | indent 6 }}
    {{- end }}
  endpoints:
    - port: http
    {{- if .Values.prometheus.monitor.interval }}
      interval: {{ .Values.prometheus.monitor.interval }}
    {{- end }}
    {{- if .Values.prometheus.monitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.prometheus.monitor.scrapeTimeout }}
    {{- end }}
    {{- if .Values.prometheus.monitor.proxyUrl }}
      proxyUrl: {{ .Values.prometheus.monitor.proxyUrl}}
    {{- end }}
    {{- if .Values.prometheus.monitor.honorLabels }}
      honorLabels: true
    {{- end }}
    {{- if .Values.prometheus.monitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml .Values.prometheus.monitor.metricRelabelings | nindent 8 }}
    {{- end }}
    {{- if .Values.prometheus.monitor.relabelings }}
      relabelings:
        {{- toYaml .Values.prometheus.monitor.relabelings | nindent 8 }}
    {{- end }}
    {{- if .Values.prometheus.monitor.scheme }}
      scheme: {{ .Values.prometheus.monitor.scheme }}
    {{- end }}
    {{- if .Values.prometheus.monitor.tlsConfig }}
      tlsConfig:
        {{- toYaml .Values.prometheus.monitor.tlsConfig | nindent 8 }}
    {{- end }}
  {{- if .Values.selfMonitor.enabled }}
    - port: metrics
    {{- if .Values.prometheus.monitor.interval }}
      interval: {{ .Values.prometheus.monitor.interval }}
    {{- end }}
    {{- if .Values.prometheus.monitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.prometheus.monitor.scrapeTimeout }}
    {{- end }}
    {{- if .Values.prometheus.monitor.proxyUrl }}
      proxyUrl: {{ .Values.prometheus.monitor.proxyUrl}}
    {{- end }}
    {{- if .Values.prometheus.monitor.honorLabels }}
      honorLabels: true
    {{- end }}
    {{- if .Values.prometheus.monitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml .Values.prometheus.monitor.metricRelabelings | nindent 8 }}
    {{- end }}
    {{- if .Values.prometheus.monitor.relabelings }}
      relabelings:
        {{- toYaml .Values.prometheus.monitor.relabelings | nindent 8 }}
    {{- end }}
    {{- if .Values.prometheus.monitor.scheme }}
      scheme: {{ .Values.prometheus.monitor.scheme }}
    {{- end }}
    {{- if .Values.prometheus.monitor.tlsConfig }}
      tlsConfig:
        {{- toYaml .Values.prometheus.monitor.tlsConfig | nindent 8 }}
    {{- end }}
  {{- end }}
{{- end }}
