{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "dubbo-admin.name" . }}
  namespace: {{ include "dubbo-admin.namespace" . }}
spec:
  policyTypes:
    - Ingress
    - Egress
{{- end }}