{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dubbo-admin.name" . }}
  namespace: {{ include "dubbo-admin.namespace" . }}
{{- end }}
---
{{- if and .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dubbo-admin-name" . }}
  namespace: {{ include "dubbo-admin-namespace" . }}
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - deployments
    verbs:
    - get
    - watch
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dubbo-admin-name" . }}
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dubbo-admin-name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dubbo-admin-name" . }}
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dubbo-admin-name" . }}-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - deployments
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dubbo-admin-name" . }}-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: dubbo-admin
    namespace: default
roleRef:
  kind: ClusterRole
  name: {{ include "dubbo-admin-name" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{- end -}}