apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: default
  labels:
    app: grafana
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "NnhlY1JVSHJpNm1MSktVRGV5cnBtZ0Jja1RUYkJmNG1ZcmdsVElKZQ=="
  ldap-toml: ""