# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: dubbo-admin ci

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  license-check:
    name: License Check
    runs-on: ubuntu-latest
    if: github.repository == 'apache/dubbo-admin'
    steps:
      - uses: actions/checkout@v4
      - name: Check License Header
        uses: apache/skywalking-eyes/header@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config: .licenserc.yaml
          mode: check

  CI:
    name: CI (${{ matrix.os }} - Go ${{ matrix.go_version }})
    runs-on: ${{ matrix.os }}
    strategy:
      # If you want to matrix build , you can append the following list.
      matrix:
        go_version:
          - "1.24"
          - "1.23"
        os:
          - ubuntu-latest
    if: github.repository == 'apache/dubbo-admin'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go_version }}
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Cache dependencies
        # ref: https://github.com/actions/cache/blob/main/examples.md#go---module
        uses: actions/cache@v4
        with:
          # Cache, works only on Linux
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          # Cache key
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Check Code Format
        run: make fmt && git status && [[ -z `git status -s` ]]
      - name: Run Unit Test
        run: make test
      # TODO(marsevilspirit): add lint
      - name: Upload test result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: "**/coverage.txt"
      - name: Coverage
        # TODO(marsevilspirit): fix coverage
        run: bash <(curl -s https://codecov.io/bash)
