name: Deploy Authority

on:
  schedule:
    - cron: '0 0/6 * * *'
  push:
    branches:
      - 'refactor-with-go'

jobs:
  docker:
    name: Doploy on ${{matrix.platform}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
#        platform: [linux/amd64, linux/arm64/v8, linux/arm/v7, linux/arm/v6]
        platform: [linux/amd64, linux/arm64/v8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: deploy/docker/authority/Dockerfile
          tags: apache/dubbo-ca:dev
          platforms: ${{matrix.platform}}
